import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from './components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Generated by muzaffar',
  description:
    'Zomin, telefon, tel, Muzaffar, muzaffar, mockapi intern, intern project,',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
